kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "reflector.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets", "configmaps"]
  verbs: ["*"]
